### ISSUE TITLE
This feature requires ASM6

### ISSUE THREAD

**Issue by zhaiyunbin** [niuxiaowei/ReplaceMethod#5]
使用最新库1.0.3
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:130)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:715)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:535)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.mi.replacemethod.gradle.ReplaceMethodTransform.traceJarFiles(ReplaceMethodTransform.groovy:158)
	at com.mi.replacemethod.gradle.ReplaceMethodTransform$traceJarFiles.callStatic(Unknown Source)
	at com.mi.replacemethod.gradle.ReplaceMethodTransform$_transform_closure1$_closure4.doCall(ReplaceMethodTransform.groovy:59)
	at com.mi.replacemethod.gradle.ReplaceMethodTransform$_transform_closure1.doCall(ReplaceMethodTransform.groovy:58)
	at com.mi.replacemethod.gradle.ReplaceMethodTransform.transform(ReplaceMethodTransform.groovy:53)

**Comment by zhaiyunbin** [comment]
版本
  classpath 'com.android.tools.build:gradle:4.1.3'
  classpath "com.github.niuxiaowei:ReplaceMethod:1.0.3"

**Comment by zhaiyunbin** [comment]
代码里还用的5
ClassVisitor cv = new ReplaceClassVisitor(Opcodes.ASM5 classWriter, config)

**Comment by kaelli** [comment]
how to fix?

**Comment by zhaiyunbin** [comment]
> how to fix?
我是把代码拉下来自己改的 
改成7就好了
Opcodes.ASM7

**Comment by niuxiaowei** [comment]
使用1.0.4库

**Comment by kaelli** [comment]
> > how to fix?
> > 我是把代码拉下来自己改的
> > 改成7就好了
> > Opcodes.ASM7

me too

**Comment by kaelli** [comment]
> 使用1.0.4库

thx
